export enum UserActivityType {
  ORDER_COMPLETED = "ORDER_COMPLETED",
  PRODUCT_COST_PRICE_CHANGE = "PRODUCT_COST_PRICE_CHANGE",
  PRODUCT_SELLING_PRICE_CHANGE = "PRODUCT_SELLING_PRICE_CHANGE",
  RECEIPT_IMPORT_CREATED = "RECEIPT_IMPORT_CREATED",
  RECEIPT_CHECK_CREATED = "RECEIPT_CHECK_CREATED",
  RECEIPT_CHECK_BALANCED = "RECEIPT_CHECK_BALANCED",
}
