version: "3.8"

services:
  # Backend Service (Deno App)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: aios-backend-app
    container_name: aios-backend-app
    restart: unless-stopped
    env_file: .env
    ports:
      - "${DOCKER_APP_PORT}:${PORT}"
    depends_on:
      - postgres
      - redis
    networks:
      - aios-network

  # PostgreSQL Service
  postgres:
    image: postgres:14-alpine
    container_name: aios-postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: "${DOCKER_POSTGRES_USER}"
      POSTGRES_PASSWORD: "${DOCKER_POSTGRES_PASSWORD}"
      POSTGRES_DB: "${DOCKER_POSTGRES_DB}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - aios-network
    ports:
      - "${DOCKER_POSTGRES_PORT}:5432"

  # Redis Service
  # redis:
  #   image: redis:alpine
  #   container_name: aios-redis
  #   restart: unless-stopped
  #   volumes:
  #     - redis-data:/data
  #   networks:
  #     - aios-network
  #   ports:
  #     - "${DOCKER_REDIS_PORT}:6379"

volumes:
  postgres-data:
  # redis-data:

networks:
  aios-network:
    driver: bridge
